<?php

namespace Database\Seeders;

use App\Domain\Core\Models\Application;
use Illuminate\Database\Seeder;

class ApplicationRegistrySeeder extends Seeder
{
    public function run(): void
    {
        $apps = [
            [
                'name' => 'GrowNet',
                'slug' => 'grownet',
                'type' => 'platform',
                'category' => 'consumer',
                'access_model' => 'customer',
                'context_support' => 'personal',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://grownet.mygrownet.com',
                'config' => ['domain_slug' => 'grownet'],
            ],
            [
                'name' => 'BizBoost',
                'slug' => 'bizboost',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://bizboost.mygrownet.com',
                'config' => ['domain_slug' => 'bizboost'],
            ],
            [
                'name' => 'GrowFinance',
                'slug' => 'growfinance',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://finance.mygrownet.com',
                'config' => ['domain_slug' => 'growfinance'],
            ],
            [
                'name' => 'GrowBiz',
                'slug' => 'growbiz',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => null,
                'config' => ['domain_slug' => 'growbiz'],
            ],
            [
                'name' => 'GrowBuilder',
                'slug' => 'growbuilder',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'both',
                'context_support' => 'both',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://growbuilder.mygrownet.com',
                'config' => ['domain_slug' => 'growbuilder'],
            ],
            [
                'name' => 'GrowMart',
                'slug' => 'growmart',
                'type' => 'consumer',
                'category' => 'consumer',
                'access_model' => 'customer',
                'context_support' => 'personal',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://growmart.mygrownet.com',
                'config' => ['domain_slug' => 'growmart'],
            ],
            [
                'name' => 'StockFlow',
                'slug' => 'stockflow',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://stockflow.mygrownet.com',
                'config' => ['domain_slug' => 'stockflow'],
            ],
            [
                'name' => 'BMS',
                'slug' => 'bms',
                'type' => 'system',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://bms.mygrownet.com',
                'config' => ['domain_slug' => 'bms'],
            ],
            [
                'name' => 'ZamStay',
                'slug' => 'zamstay',
                'type' => 'consumer',
                'category' => 'consumer',
                'access_model' => 'customer',
                'context_support' => 'personal',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://zamstay.mygrownet.com',
                'config' => ['domain_slug' => 'zamstay'],
            ],
            [
                'name' => 'PrimeEdge Advisory',
                'slug' => 'primeedge',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'both',
                'context_support' => 'both',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://primeedge.mygrownet.com',
                'config' => ['domain_slug' => 'primeedge'],
            ],
            [
                'name' => 'BizDocs',
                'slug' => 'bizdocs',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'organization_members',
                'context_support' => 'organization',
                'requires_organization_context' => true,
                'subscription_required' => true,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://bizdocs.mygrownet.com',
                'config' => ['domain_slug' => 'bizdocs'],
            ],
            [
                'name' => 'LifePlus',
                'slug' => 'lifeplus',
                'type' => 'consumer',
                'category' => 'consumer',
                'access_model' => 'customer',
                'context_support' => 'personal',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => null,
                'config' => null,
            ],
            [
                'name' => 'GrowStorage',
                'slug' => 'growstorage',
                'type' => 'shared',
                'category' => 'shared',
                'access_model' => 'customer',
                'context_support' => 'both',
                'requires_organization_context' => false,
                'subscription_required' => false,
                'lifecycle' => 'active',
                'operational_status' => 'online',
                'is_visible' => true,
                'url' => 'https://growstorage.mygrownet.com',
                'config' => ['domain_slug' => 'growstorage'],
            ],
            [
                'name' => 'Quick Invoice',
                'slug' => 'quick-invoice',
                'type' => 'business',
                'category' => 'business',
                'access_model' => 'customer',
                'context_support' => 'personal',
                'requires_organization_context' => false,
                'subscription_required' => true,
                'lifecycle' => 'legacy',
                'operational_status' => 'online',
                'is_visible' => false,
                'url' => null,
                'config' => null,
            ],
        ];

        foreach ($apps as $app) {
            Application::firstOrCreate(
                ['slug' => $app['slug']],
                $app,
            );
        }
    }
}
