<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BizBoostTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // Social Media Templates
            [
                'name' => 'Product Showcase',
                'slug' => 'product-showcase',
                'description' => 'Highlight a single product with price and description',
                'category' => 'social',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'product',
                    'layout' => 'centered',
                    'caption' => "✨ Introducing [PRODUCT NAME]! ✨\n\nLooking for quality? Look no further! Our [PRODUCT NAME] is exactly what you need.\n\n💰 Only K[PRICE]\n\n📍 Visit us today or DM to order!",
                    'hashtags' => ['ShopLocal', 'QualityProducts', 'MadeInZambia', 'SmallBusiness'],
                    'cta' => '👉 DM us to order or visit our shop today!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Sale Announcement',
                'slug' => 'sale-announcement',
                'description' => 'Announce discounts and special offers',
                'category' => 'promotion',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'sale',
                    'layout' => 'bold',
                    'caption' => "🔥 MASSIVE SALE ALERT! 🔥\n\nGet [DISCOUNT]% OFF on selected items!\n\n⏰ Limited time only - Don't miss out!\n\n📅 Valid until [DATE]",
                    'hashtags' => ['Sale', 'Discount', 'LimitedOffer', 'ShopNow', 'Zambia'],
                    'cta' => '🛒 Shop now before it\'s gone!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'New Arrival',
                'slug' => 'new-arrival',
                'description' => 'Announce new products or services',
                'category' => 'social',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'announcement',
                    'layout' => 'modern',
                    'caption' => "🆕 NEW ARRIVAL! 🆕\n\nWe're excited to introduce [PRODUCT NAME] to our collection!\n\n✅ [Feature 1]\n✅ [Feature 2]\n✅ [Feature 3]\n\nBe the first to get yours!",
                    'hashtags' => ['NewArrival', 'JustIn', 'NewProduct', 'ShopLocal'],
                    'cta' => '📲 Order now via DM or WhatsApp!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // Salon Templates
            [
                'name' => 'Salon Price List',
                'slug' => 'salon-price-list',
                'description' => 'Display your salon services and prices',
                'category' => 'pricing',
                'industry' => 'salon',
                'template_data' => json_encode([
                    'type' => 'price_list',
                    'layout' => 'elegant',
                    'caption' => "💇‍♀️ OUR SERVICES & PRICES 💇‍♀️\n\n✂️ Haircut - K[PRICE]\n💆‍♀️ Treatment - K[PRICE]\n💅 Nails - K[PRICE]\n\n📍 [Your Location]\n📞 [Your Number]",
                    'hashtags' => ['Salon', 'HairSalon', 'Beauty', 'Lusaka', 'ZambiaSalon'],
                    'cta' => '📱 Book your appointment today!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Hair Transformation',
                'slug' => 'hair-transformation',
                'description' => 'Before and after hair styling showcase',
                'category' => 'social',
                'industry' => 'salon',
                'template_data' => json_encode([
                    'type' => 'before_after',
                    'layout' => 'split',
                    'caption' => "✨ TRANSFORMATION TUESDAY ✨\n\nSwipe to see the magic! ➡️\n\nOur client came in for a [SERVICE] and left feeling absolutely gorgeous!\n\n💇‍♀️ Service: [SERVICE NAME]\n⏱️ Time: [DURATION]\n💰 Price: K[PRICE]",
                    'hashtags' => ['HairTransformation', 'BeforeAndAfter', 'SalonLife', 'HairGoals'],
                    'cta' => '📲 Book your transformation - Link in bio!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => true,
                'is_featured' => false,
            ],
            // Restaurant Templates
            [
                'name' => 'Menu Special',
                'slug' => 'menu-special',
                'description' => 'Highlight daily specials or featured dishes',
                'category' => 'menu',
                'industry' => 'restaurant',
                'template_data' => json_encode([
                    'type' => 'menu_item',
                    'layout' => 'appetizing',
                    'caption' => "🍽️ TODAY'S SPECIAL 🍽️\n\n[DISH NAME]\n\n[Description of the dish and what makes it special]\n\n💰 Only K[PRICE]\n\n⏰ Available today only!",
                    'hashtags' => ['FoodieZambia', 'LusakaEats', 'TodaysSpecial', 'ZambianFood'],
                    'cta' => '📍 Visit us at [Location] or call [Number] to order!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Restaurant Menu',
                'slug' => 'restaurant-menu',
                'description' => 'Full menu layout for restaurants',
                'category' => 'menu',
                'industry' => 'restaurant',
                'template_data' => json_encode([
                    'type' => 'full_menu',
                    'layout' => 'classic',
                    'caption' => "📋 OUR MENU 📋\n\n🥗 STARTERS\n• [Item] - K[Price]\n• [Item] - K[Price]\n\n🍖 MAINS\n• [Item] - K[Price]\n• [Item] - K[Price]\n\n🍰 DESSERTS\n• [Item] - K[Price]\n\n📍 [Location]\n📞 [Phone]",
                    'hashtags' => ['Restaurant', 'Menu', 'FoodLovers', 'DineWithUs'],
                    'cta' => '🍴 Reserve your table today!',
                ]),
                'width' => 1080,
                'height' => 1920,
                'is_premium' => true,
                'is_featured' => false,
            ],
            // Boutique Templates
            [
                'name' => 'Fashion Collection',
                'slug' => 'fashion-collection',
                'description' => 'Showcase your latest fashion items',
                'category' => 'social',
                'industry' => 'boutique',
                'template_data' => json_encode([
                    'type' => 'collection',
                    'layout' => 'grid',
                    'caption' => "👗 NEW COLLECTION ALERT! 👗\n\nIntroducing our [COLLECTION NAME] collection!\n\n✨ Stylish\n✨ Affordable\n✨ Made for you\n\nSizes: XS - XXL\nPrices from K[PRICE]",
                    'hashtags' => ['Fashion', 'NewCollection', 'Style', 'ZambiaFashion', 'Boutique'],
                    'cta' => '🛍️ Shop now - DM or visit our store!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            // Flyer Templates
            [
                'name' => 'Event Flyer',
                'slug' => 'event-flyer',
                'description' => 'Promote events and special occasions',
                'category' => 'flyer',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'event',
                    'layout' => 'dynamic',
                    'caption' => "🎉 YOU'RE INVITED! 🎉\n\n[EVENT NAME]\n\n📅 Date: [DATE]\n⏰ Time: [TIME]\n📍 Venue: [VENUE]\n\n[Brief description of what to expect]\n\n🎟️ Entry: K[PRICE] / Free",
                    'hashtags' => ['Event', 'Zambia', 'WeekendPlans', 'ThingsToDoInLusaka'],
                    'cta' => '📲 RSVP now - Limited spots available!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Grand Opening',
                'slug' => 'grand-opening',
                'description' => 'Announce your business opening',
                'category' => 'flyer',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'opening',
                    'layout' => 'celebration',
                    'caption' => "🎊 GRAND OPENING! 🎊\n\n[BUSINESS NAME] is officially OPEN!\n\n📅 [DATE]\n📍 [ADDRESS]\n\n🎁 Special opening offers:\n• [Offer 1]\n• [Offer 2]\n\nCome celebrate with us!",
                    'hashtags' => ['GrandOpening', 'NewBusiness', 'Zambia', 'SupportLocal'],
                    'cta' => '🎉 See you there! Share with friends!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => true,
            ],
            // Barbershop Templates
            [
                'name' => 'Barbershop Price List',
                'slug' => 'barbershop-price-list',
                'description' => 'Display your barbershop services and prices',
                'category' => 'pricing',
                'industry' => 'barbershop',
                'template_data' => json_encode([
                    'type' => 'price_list',
                    'layout' => 'bold',
                    'caption' => "💈 OUR SERVICES 💈\n\n✂️ Haircut - K[PRICE]\n🧔 Beard Trim - K[PRICE]\n💇‍♂️ Haircut + Beard - K[PRICE]\n🧴 Hot Towel Shave - K[PRICE]\n\n📍 [Your Location]\n📞 [Your Number]",
                    'hashtags' => ['Barbershop', 'FreshCuts', 'MensGrooming', 'Lusaka'],
                    'cta' => '💈 Walk-ins welcome! Book your spot today!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Fresh Cut Showcase',
                'slug' => 'fresh-cut-showcase',
                'description' => 'Show off your best haircut work',
                'category' => 'social',
                'industry' => 'barbershop',
                'template_data' => json_encode([
                    'type' => 'showcase',
                    'layout' => 'modern',
                    'caption' => "✂️ FRESH CUT FRIDAY ✂️\n\nAnother satisfied customer leaving the chair looking sharp! 🔥\n\n💇‍♂️ Style: [STYLE NAME]\n💰 Price: K[PRICE]\n\nWho's next?",
                    'hashtags' => ['FreshCut', 'Barber', 'MensHair', 'ZambiaBarber'],
                    'cta' => '📲 Book your appointment - DM or call!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // Grocery Templates
            [
                'name' => 'Weekly Deals',
                'slug' => 'grocery-weekly-deals',
                'description' => 'Announce weekly specials and deals',
                'category' => 'promotion',
                'industry' => 'grocery',
                'template_data' => json_encode([
                    'type' => 'deals',
                    'layout' => 'grid',
                    'caption' => "🛒 THIS WEEK'S DEALS! 🛒\n\n🥬 Fresh Vegetables - K[PRICE]/bundle\n🍚 Rice 25kg - K[PRICE]\n🛢️ Cooking Oil 2L - K[PRICE]\n🧴 Washing Powder - K[PRICE]\n\n📅 Valid: [DATE] - [DATE]\n📍 [Location]",
                    'hashtags' => ['GroceryDeals', 'WeeklySpecials', 'ShopLocal', 'Zambia'],
                    'cta' => '🛒 Come early for the best picks!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Fresh Arrivals',
                'slug' => 'grocery-fresh-arrivals',
                'description' => 'Announce fresh produce arrivals',
                'category' => 'social',
                'industry' => 'grocery',
                'template_data' => json_encode([
                    'type' => 'announcement',
                    'layout' => 'fresh',
                    'caption' => "🥬 FRESH ARRIVALS! 🥬\n\nJust in from the farm:\n\n✅ [Product 1]\n✅ [Product 2]\n✅ [Product 3]\n\nFresh, quality produce at affordable prices!\n\n📍 [Location]\n⏰ Open [Hours]",
                    'hashtags' => ['FreshProduce', 'Grocery', 'FarmFresh', 'ZambiaFood'],
                    'cta' => '🏃 Come early - limited stock!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // Hardware Templates
            [
                'name' => 'Hardware Stock Alert',
                'slug' => 'hardware-stock-alert',
                'description' => 'Announce new stock arrivals',
                'category' => 'social',
                'industry' => 'hardware',
                'template_data' => json_encode([
                    'type' => 'stock',
                    'layout' => 'industrial',
                    'caption' => "🏗️ NEW STOCK ALERT! 🏗️\n\nJust arrived:\n\n🧱 Cement - K[PRICE]/bag\n🪵 Timber - K[PRICE]\n🔩 Roofing Sheets - K[PRICE]\n🎨 Paint - K[PRICE]/bucket\n\n📍 [Location]\n📞 [Phone]",
                    'hashtags' => ['Hardware', 'BuildingMaterials', 'Construction', 'Zambia'],
                    'cta' => '🚚 Delivery available! Call to order.',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Contractor Special',
                'slug' => 'hardware-contractor-special',
                'description' => 'Special offers for contractors',
                'category' => 'promotion',
                'industry' => 'hardware',
                'template_data' => json_encode([
                    'type' => 'promotion',
                    'layout' => 'bold',
                    'caption' => "👷 CONTRACTOR SPECIAL! 👷\n\nBulk orders get special discounts!\n\n📦 10+ bags cement - [X]% OFF\n📦 50+ roofing sheets - [X]% OFF\n📦 Bulk timber - Special pricing\n\n📞 Call for quotes: [Phone]",
                    'hashtags' => ['Contractor', 'BulkOrder', 'Hardware', 'Building'],
                    'cta' => '📱 Call now for your bulk quote!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // Electronics Templates
            [
                'name' => 'Phone Deals',
                'slug' => 'electronics-phone-deals',
                'description' => 'Showcase phone deals and offers',
                'category' => 'promotion',
                'industry' => 'electronics',
                'template_data' => json_encode([
                    'type' => 'product',
                    'layout' => 'tech',
                    'caption' => "📱 PHONE DEALS! 📱\n\n[PHONE MODEL]\n\n✅ [Spec 1]\n✅ [Spec 2]\n✅ [Spec 3]\n\n💰 Only K[PRICE]\n🎁 FREE: Screen protector + Case\n\n📍 [Location]",
                    'hashtags' => ['Phones', 'TechDeals', 'Electronics', 'Zambia'],
                    'cta' => '📲 DM or visit us to grab yours!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Repair Services',
                'slug' => 'electronics-repair',
                'description' => 'Promote phone and electronics repair',
                'category' => 'service',
                'industry' => 'electronics',
                'template_data' => json_encode([
                    'type' => 'service',
                    'layout' => 'clean',
                    'caption' => "🔧 REPAIR SERVICES 🔧\n\n📱 Screen Replacement - K[PRICE]\n🔋 Battery Replacement - K[PRICE]\n💧 Water Damage Repair - K[PRICE]\n🔌 Charging Port Fix - K[PRICE]\n\n⏱️ Most repairs done same day!\n📍 [Location]",
                    'hashtags' => ['PhoneRepair', 'Electronics', 'TechSupport', 'Lusaka'],
                    'cta' => '📞 Bring your device in for a free diagnosis!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // Mobile Money Templates
            [
                'name' => 'Mobile Money Services',
                'slug' => 'mobile-money-services',
                'description' => 'List your mobile money services',
                'category' => 'service',
                'industry' => 'mobile_money',
                'template_data' => json_encode([
                    'type' => 'service_list',
                    'layout' => 'clean',
                    'caption' => "💰 MOBILE MONEY SERVICES 💰\n\n✅ Cash In / Cash Out\n✅ Bill Payments\n✅ Airtime Top-up\n✅ Money Transfers\n✅ ZESCO Payments\n\n📍 [Location]\n⏰ Open: [Hours]\n\n💵 Float always available!",
                    'hashtags' => ['MobileMoney', 'MTNMomo', 'AirtelMoney', 'Zambia'],
                    'cta' => '📍 Visit us for quick, reliable service!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => true,
            ],
            // Photography Templates
            [
                'name' => 'Photography Packages',
                'slug' => 'photography-packages',
                'description' => 'Display your photography packages',
                'category' => 'pricing',
                'industry' => 'photography',
                'template_data' => json_encode([
                    'type' => 'packages',
                    'layout' => 'elegant',
                    'caption' => "📸 PHOTOGRAPHY PACKAGES 📸\n\n🥉 BASIC - K[PRICE]\n• 1 hour session\n• 20 edited photos\n\n🥈 STANDARD - K[PRICE]\n• 2 hour session\n• 50 edited photos\n• 1 location\n\n🥇 PREMIUM - K[PRICE]\n• Full day coverage\n• Unlimited photos\n• Album included",
                    'hashtags' => ['Photography', 'Photographer', 'ZambiaPhotographer', 'BookNow'],
                    'cta' => '📲 Book your session - DM or call!',
                ]),
                'width' => 1080,
                'height' => 1350,
                'is_premium' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Portfolio Showcase',
                'slug' => 'photography-portfolio',
                'description' => 'Show off your best photography work',
                'category' => 'social',
                'industry' => 'photography',
                'template_data' => json_encode([
                    'type' => 'portfolio',
                    'layout' => 'gallery',
                    'caption' => "📸 FROM THE PORTFOLIO 📸\n\n[Brief description of the shoot]\n\n📅 Shot: [Event/Occasion]\n📍 Location: [Location]\n\nCapturing moments that last forever ✨",
                    'hashtags' => ['Portfolio', 'Photography', 'Moments', 'ZambiaPhotography'],
                    'cta' => '📲 Book your session - Link in bio!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            // General Templates
            [
                'name' => 'Customer Testimonial',
                'slug' => 'customer-testimonial',
                'description' => 'Share customer reviews and feedback',
                'category' => 'social',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'testimonial',
                    'layout' => 'quote',
                    'caption' => "💬 WHAT OUR CUSTOMERS SAY 💬\n\n\"[Customer quote about your product/service]\"\n\n- [Customer Name]\n\nThank you for trusting us! 🙏\n\nWant to experience the same? Visit us today!",
                    'hashtags' => ['CustomerReview', 'Testimonial', 'HappyCustomer', 'ThankYou'],
                    'cta' => '⭐ Join our happy customers - Shop with us!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Motivational Monday',
                'slug' => 'motivational-monday',
                'description' => 'Weekly motivation for your audience',
                'category' => 'engagement',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'motivation',
                    'layout' => 'minimal',
                    'caption' => "💪 MOTIVATION MONDAY 💪\n\n\"[Inspirational quote]\"\n\nStart your week with purpose! What are your goals this week?\n\n👇 Share in the comments!",
                    'hashtags' => ['MotivationMonday', 'MondayMotivation', 'Inspiration', 'Goals'],
                    'cta' => '💭 Drop your goals below!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Behind The Scenes',
                'slug' => 'behind-the-scenes',
                'description' => 'Show your business process and team',
                'category' => 'engagement',
                'industry' => null,
                'template_data' => json_encode([
                    'type' => 'bts',
                    'layout' => 'casual',
                    'caption' => "👀 BEHIND THE SCENES 👀\n\nEver wondered how we [process/make/do something]?\n\nHere's a sneak peek into our [workshop/kitchen/office]!\n\n[Brief description of what's happening]",
                    'hashtags' => ['BehindTheScenes', 'BTS', 'SmallBusiness', 'MeetTheTeam'],
                    'cta' => '🔔 Follow for more behind-the-scenes content!',
                ]),
                'width' => 1080,
                'height' => 1080,
                'is_premium' => false,
                'is_featured' => false,
            ],
        ];

        foreach ($templates as $template) {
            DB::table('bizboost_templates')->updateOrInsert(
                ['slug' => $template['slug']],
                array_merge($template, [
                    'is_active' => true,
                    'usage_count' => 0,
                    'sort_order' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('BizBoost templates seeded successfully!');
    }
}
