DELETE FROM professional_levels;

INSERT INTO professional_levels (level, name, slug, network_size, role, bp_required, lp_required, min_time, additional_requirements, milestone_bonus, profit_share_multiplier, commission_rate, color, benefits, sort_order, is_active, created_at, updated_at) VALUES
(1, 'Associate', 'associate', '3', 'New member, learning', 100, 0, 'Immediate', 'Registration complete', NULL, '1.0x', '15%', 'gray', '["Basic educational content","Peer circle access","7-level commission structure (15%)","Monthly qualification: 100 BP","Profit-sharing: 1.0x base share"]', 1, 1, NOW(), NOW()),
(2, 'Professional', 'professional', '9', 'Skilled member, applying', 200, 2500, '1 month active', '3 direct referrals', 'K500', '1.2x', '10%', 'blue', '["Advanced educational content","Group mentorship access","Level 2 commissions (10%)","Monthly qualification: 200 BP","Profit-sharing: 1.2x base share","Promotion bonus: K500"]', 2, 1, NOW(), NOW()),
(3, 'Senior', 'senior', '27', 'Experienced, team building', 300, 4000, '3 months active', '2 active direct referrals, 1 course completed', 'K1,500 + Smartphone', '1.5x', '8%', 'green', '["Premium content library","1-on-1 mentorship sessions","Level 3 commissions (8%)","Team building bonuses","Monthly qualification: 300 BP","Profit-sharing: 1.5x base share","Promotion bonus: K1,500 + Smartphone"]', 3, 1, NOW(), NOW()),
(4, 'Manager', 'manager', '81', 'Team leader', 400, 12500, '6 months active', '1 Professional in downline, 3 courses completed', 'K5,000 + Motorbike', '2.0x', '6%', 'purple', '["Leadership training programs","Level 4 commissions (6%)","Team performance bonuses","Booster fund: K5,000","Monthly qualification: 400 BP","Profit-sharing: 2.0x base share","Promotion bonus: K5,000 + Motorbike"]', 4, 1, NOW(), NOW()),
(5, 'Director', 'director', '243', 'Strategic leader', 500, 60000, '12 months active', '1 Senior in downline, 5 courses completed', 'K15,000 + Vehicle', '2.5x', '4%', 'indigo', '["Strategic leadership content","Level 5 commissions (4%)","Business facilitation services","Booster fund: K15,000","Monthly qualification: 500 BP","Profit-sharing: 2.5x base share","Promotion bonus: K15,000 + Vehicle"]', 5, 1, NOW(), NOW()),
(6, 'Executive', 'executive', '729', 'Top performer', 600, 160000, '18 months active', '1 Manager in downline, 10 courses completed', 'K50,000 + Luxury', '3.0x', '3%', 'yellow', '["Executive coaching access","Level 6 commissions (3%)","Innovation lab participation","Booster fund: K50,000","Monthly qualification: 600 BP","Profit-sharing: 3.0x base share","Promotion bonus: K50,000 + Luxury"]', 6, 1, NOW(), NOW()),
(7, 'Ambassador', 'ambassador', '2,187', 'Brand representative', 800, 350000, '24 months active', '1 Director in downline, 15 courses, 1 project participation', 'K150,000 + Property', '4.0x', '2%', 'red', '["VIP brand ambassador status","Level 7 commissions (2%)","Exclusive events & retreats","Booster fund: K150,000","Monthly qualification: 800 BP","Profit-sharing: 4.0x base share (MAX)","Promotion bonus: K150,000 + Property"]', 7, 1, NOW(), NOW());
