<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Infrastructure\Persistence\Eloquent\Workshop\WorkshopModel;
use Illuminate\Support\Str;

class WorkshopSeeder extends Seeder
{
    public function run(): void
    {
        $workshops = [
            [
                'title' => 'Financial Literacy Fundamentals',
                'slug' => 'financial-literacy-fundamentals',
                'description' => 'Learn the basics of personal finance, budgeting, saving, and investing. Perfect for beginners looking to take control of their financial future.',
                'category' => 'financial_literacy',
                'delivery_format' => 'online',
                'price' => 150.00,
                'max_participants' => 50,
                'lp_reward' => 50,
                'bp_reward' => 100,
                'start_date' => now()->addDays(7)->setTime(14, 0),
                'end_date' => now()->addDays(7)->setTime(17, 0),
                'location' => null,
                'meeting_link' => 'https://zoom.us/j/example',
                'requirements' => 'Basic understanding of money management. Notebook and pen for taking notes.',
                'learning_outcomes' => 'Understand budgeting principles, learn saving strategies, basics of investing, debt management techniques.',
                'instructor_name' => 'John Banda',
                'instructor_bio' => 'Certified Financial Planner with 10+ years experience in personal finance education.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
            [
                'title' => 'Digital Marketing Mastery',
                'slug' => 'digital-marketing-mastery',
                'description' => 'Master social media marketing, content creation, and online advertising to grow your business or personal brand.',
                'category' => 'marketing',
                'delivery_format' => 'hybrid',
                'price' => 300.00,
                'max_participants' => 30,
                'lp_reward' => 75,
                'bp_reward' => 150,
                'start_date' => now()->addDays(14)->setTime(9, 0),
                'end_date' => now()->addDays(14)->setTime(16, 0),
                'location' => 'Lusaka Business Hub, Cairo Road',
                'meeting_link' => 'https://zoom.us/j/example2',
                'requirements' => 'Smartphone or laptop with internet connection. Active social media accounts.',
                'learning_outcomes' => 'Create effective social media campaigns, understand digital advertising, content strategy, analytics and metrics.',
                'instructor_name' => 'Grace Mwale',
                'instructor_bio' => 'Digital Marketing Specialist with successful campaigns for 50+ businesses.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
            [
                'title' => 'Leadership & Team Building',
                'slug' => 'leadership-team-building',
                'description' => 'Develop essential leadership skills, learn to motivate teams, and build a culture of success in your organization.',
                'category' => 'leadership',
                'delivery_format' => 'physical',
                'price' => 500.00,
                'max_participants' => 25,
                'lp_reward' => 100,
                'bp_reward' => 200,
                'start_date' => now()->addDays(21)->setTime(8, 0),
                'end_date' => now()->addDays(22)->setTime(17, 0),
                'location' => 'Taj Pamodzi Hotel, Lusaka',
                'meeting_link' => null,
                'requirements' => 'Open mind and willingness to participate in group activities. Business casual attire.',
                'learning_outcomes' => 'Leadership styles and when to use them, team motivation techniques, conflict resolution, performance management.',
                'instructor_name' => 'Dr. Peter Phiri',
                'instructor_bio' => 'Leadership consultant and executive coach with 15 years experience training corporate leaders.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
            [
                'title' => 'Small Business Management',
                'slug' => 'small-business-management',
                'description' => 'Everything you need to start and run a successful small business. From planning to execution and growth strategies.',
                'category' => 'business_skills',
                'delivery_format' => 'online',
                'price' => 250.00,
                'max_participants' => 40,
                'lp_reward' => 60,
                'bp_reward' => 120,
                'start_date' => now()->addDays(10)->setTime(18, 0),
                'end_date' => now()->addDays(10)->setTime(21, 0),
                'location' => null,
                'meeting_link' => 'https://zoom.us/j/example3',
                'requirements' => 'Business idea or existing small business. Willingness to learn and implement.',
                'learning_outcomes' => 'Business planning, financial management, marketing basics, customer service, scaling strategies.',
                'instructor_name' => 'Moses Tembo',
                'instructor_bio' => 'Serial entrepreneur who has built and sold 3 successful businesses.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
            [
                'title' => 'Personal Development & Goal Setting',
                'slug' => 'personal-development-goal-setting',
                'description' => 'Transform your life through effective goal setting, time management, and personal growth strategies.',
                'category' => 'personal_development',
                'delivery_format' => 'online',
                'price' => 200.00,
                'max_participants' => null, // Unlimited
                'lp_reward' => 40,
                'bp_reward' => 80,
                'start_date' => now()->addDays(5)->setTime(19, 0),
                'end_date' => now()->addDays(5)->setTime(21, 0),
                'location' => null,
                'meeting_link' => 'https://zoom.us/j/example4',
                'requirements' => 'Journal or notebook for exercises. Open mind and commitment to personal growth.',
                'learning_outcomes' => 'SMART goal setting, time management techniques, habit formation, overcoming obstacles, accountability systems.',
                'instructor_name' => 'Sarah Lungu',
                'instructor_bio' => 'Life coach and motivational speaker who has helped 1000+ people achieve their goals.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
            [
                'title' => 'Introduction to Technology & Digital Tools',
                'slug' => 'intro-technology-digital-tools',
                'description' => 'Get comfortable with essential digital tools and technology for modern business and personal productivity.',
                'category' => 'technology',
                'delivery_format' => 'hybrid',
                'price' => 180.00,
                'max_participants' => 35,
                'lp_reward' => 45,
                'bp_reward' => 90,
                'start_date' => now()->addDays(12)->setTime(10, 0),
                'end_date' => now()->addDays(12)->setTime(15, 0),
                'location' => 'MyGrowNet Training Center',
                'meeting_link' => 'https://zoom.us/j/example5',
                'requirements' => 'Smartphone or computer. Basic computer literacy helpful but not required.',
                'learning_outcomes' => 'Essential software tools, cloud storage, online collaboration, digital security basics, productivity apps.',
                'instructor_name' => 'David Mulenga',
                'instructor_bio' => 'IT trainer specializing in making technology accessible to everyone.',
                'featured_image' => null,
                'status' => 'published',
                'created_by' => 1,
            ],
        ];

        foreach ($workshops as $workshop) {
            WorkshopModel::create($workshop);
        }

        $this->command->info('Created ' . count($workshops) . ' sample workshops');
    }
}
