import defaultTheme from 'tailwindcss/defaultTheme';

/**
 * GrowStream design system — dark theme, static values.
 * No CSS-variable indirection: utilities resolve to concrete hex colors so
 * there is nothing for Tailwind to purge or for other stylesheets to override.
 * Palette = GrowStream dark landing (warm charcoal + terracotta).
 */
/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    important: true,
    content: [
        './resources/js/pages/GrowStream/**/*.vue',
        './resources/js/Layouts/GrowStreamLayout.vue',
        './resources/js/layouts/GrowStreamLayout.vue',
        './resources/js/components/GrowStream/**/*.vue',
        './resources/js/composables/**/*.ts',
        './resources/views/growstream.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'on-background': '#f4ede9',
                'surface-container-highest': '#332924',
                'surface-container': '#241d19',
                'on-error-container': '#ffb4ab',
                'on-primary-fixed-variant': '#ffd9c9',
                'secondary-container': '#2c3e5c',
                'primary-container': '#5c2000',
                'surface-container-lowest': '#0d0a08',
                'secondary-fixed-dim': '#b6c7e7',
                'on-surface-variant': '#d8c2bc',
                'error': '#ffb4ab',
                'background': '#14100e',
                'outline': '#8d7168',
                'surface-container-high': '#2b231f',
                'on-error': '#690005',
                'inverse-primary': '#ffb59c',
                'surface-bright': '#241d19',
                'on-secondary-fixed': '#091c34',
                'error-container': '#93000a',
                'on-primary-container': '#ffd9c9',
                'on-tertiary': '#ffffff',
                'primary': '#e2571f',
                'inverse-on-surface': '#14100e',
                'on-primary': '#ffffff',
                'secondary-fixed': '#d5e3ff',
                'primary-fixed-dim': '#ffb59c',
                'tertiary-container': '#986d00',
                'surface-variant': '#241d19',
                'on-surface': '#f4ede9',
                'secondary': '#a8c0e6',
                'primary-fixed': '#ffdbcf',
                'on-tertiary-container': '#fffbff',
                'on-primary-fixed': '#390c00',
                'outline-variant': '#4a3a34',
                'surface': '#14100e',
                'inverse-surface': '#2e3132',
                'surface-dim': '#0d0a08',
                'surface-tint': '#e2571f',
                'tertiary': '#795600',
                'on-tertiary-fixed-variant': '#5e4200',
                'on-secondary-fixed-variant': '#374762',
                'on-secondary-container': '#d5e3ff',
                'surface-container-low': '#1c1613',
                'tertiary-fixed': '#ffdea8',
                'tertiary-fixed-dim': '#ffba20',
                'on-tertiary-fixed': '#271900',
                'on-secondary': '#1a2740',
            },
            fontFamily: {
                'display-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'body-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['56px', { lineHeight: '62px', letterSpacing: '-0.02em', fontWeight: '900' }],
                'headline-lg': ['44px', { lineHeight: '52px', fontWeight: '800' }],
                'headline-lg-mobile': ['30px', { lineHeight: '38px', fontWeight: '800' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'body-lg': ['19px', { lineHeight: '30px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'gutter': '1rem',
                'margin-mobile': '1rem',
                'margin-desktop': '2rem',
            },
        },
    },
};
