import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/js/pages/GrowStream/**/*.vue',
        './resources/js/Layouts/GrowStreamLayout.vue',
        './resources/js/layouts/GrowStreamLayout.vue',
        './resources/js/components/GrowStream/**/*.vue',
        './resources/js/composables/**/*.ts',
        './resources/views/growstream.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'on-background': '#191c1d',
                'surface-container-highest': '#e1e3e4',
                'surface-container': '#edeeef',
                'on-error-container': '#93000a',
                'on-primary-fixed-variant': '#822700',
                'secondary-container': '#ccdefe',
                'primary-container': '#cc4911',
                'surface-container-lowest': '#ffffff',
                'secondary-fixed-dim': '#b6c7e7',
                'on-surface-variant': '#594139',
                'error': '#ba1a1a',
                'background': '#f8f9fa',
                'outline': '#8d7168',
                'surface-container-high': '#e7e8e9',
                'on-error': '#ffffff',
                'inverse-primary': '#ffb59c',
                'surface-bright': '#f8f9fa',
                'on-secondary-fixed': '#091c34',
                'error-container': '#ffdad6',
                'on-primary-container': '#fffbff',
                'on-tertiary': '#ffffff',
                'primary': '#a73400',
                'inverse-on-surface': '#f0f1f2',
                'on-primary': '#ffffff',
                'secondary-fixed': '#d5e3ff',
                'primary-fixed-dim': '#ffb59c',
                'tertiary-container': '#986d00',
                'surface-variant': '#e1e3e4',
                'on-surface': '#191c1d',
                'secondary': '#4f5f7b',
                'primary-fixed': '#ffdbcf',
                'on-tertiary-container': '#fffbff',
                'on-primary-fixed': '#390c00',
                'outline-variant': '#e1bfb4',
                'surface': '#f8f9fa',
                'inverse-surface': '#2e3132',
                'surface-dim': '#d9dadb',
                'surface-tint': '#ab3600',
                'tertiary': '#795600',
                'on-tertiary-fixed-variant': '#5e4200',
                'on-secondary-fixed-variant': '#374762',
                'on-secondary-container': '#51617d',
                'surface-container-low': '#f3f4f5',
                'tertiary-fixed': '#ffdea8',
                'tertiary-fixed-dim': '#ffba20',
                'on-tertiary-fixed': '#271900',
                'on-secondary': '#ffffff',
            },
            fontFamily: {
                'display-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'body-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'gutter': '1rem',
                'margin-mobile': '1rem',
                'margin-desktop': '2rem',
            },
        },
    },
};
