import defaultTheme from 'tailwindcss/defaultTheme';

/**
 * GrowStream design system — Sunset Terracotta.
 * Colors are CSS variables that flip between light and dark via `.dark`:
 *   - light values defined on `:root` (in growstream.css)
 *   - dark values defined on `.dark` (in growstream.css)
 * Tailwind classes (bg-surface, text-on-surface, etc.) automatically switch.
 */
/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/js/pages/GrowStream/**/*.vue',
        './resources/js/Layouts/GrowStreamLayout.vue',
        './resources/js/layouts/GrowStreamLayout.vue',
        './resources/js/components/GrowStream/**/*.vue',
        './resources/js/composables/**/*.ts',
        './resources/views/growstream.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'on-background': 'rgb(var(--gs-on-background) / <alpha-value>)',
                'surface-container-highest': 'rgb(var(--gs-surface-container-highest) / <alpha-value>)',
                'surface-container': 'rgb(var(--gs-surface-container) / <alpha-value>)',
                'on-error-container': 'rgb(var(--gs-on-error-container) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--gs-on-primary-fixed-variant) / <alpha-value>)',
                'secondary-container': 'rgb(var(--gs-secondary-container) / <alpha-value>)',
                'primary-container': 'rgb(var(--gs-primary-container) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--gs-surface-container-lowest) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--gs-secondary-fixed-dim) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--gs-on-surface-variant) / <alpha-value>)',
                'error': 'rgb(var(--gs-error) / <alpha-value>)',
                'background': 'rgb(var(--gs-background) / <alpha-value>)',
                'outline': 'rgb(var(--gs-outline) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--gs-surface-container-high) / <alpha-value>)',
                'on-error': 'rgb(var(--gs-on-error) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--gs-inverse-primary) / <alpha-value>)',
                'surface-bright': 'rgb(var(--gs-surface-bright) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--gs-on-secondary-fixed) / <alpha-value>)',
                'error-container': 'rgb(var(--gs-error-container) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--gs-on-primary-container) / <alpha-value>)',
                'on-tertiary': 'rgb(var(--gs-on-tertiary) / <alpha-value>)',
                'primary': 'rgb(var(--gs-primary) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--gs-inverse-on-surface) / <alpha-value>)',
                'on-primary': 'rgb(var(--gs-on-primary) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--gs-secondary-fixed) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--gs-primary-fixed-dim) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--gs-tertiary-container) / <alpha-value>)',
                'surface-variant': 'rgb(var(--gs-surface-variant) / <alpha-value>)',
                'on-surface': 'rgb(var(--gs-on-surface) / <alpha-value>)',
                'secondary': 'rgb(var(--gs-secondary) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--gs-primary-fixed) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--gs-on-tertiary-container) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--gs-on-primary-fixed) / <alpha-value>)',
                'outline-variant': 'rgb(var(--gs-outline-variant) / <alpha-value>)',
                'surface': 'rgb(var(--gs-surface) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--gs-inverse-surface) / <alpha-value>)',
                'surface-dim': 'rgb(var(--gs-surface-dim) / <alpha-value>)',
                'surface-tint': 'rgb(var(--gs-surface-tint) / <alpha-value>)',
                'tertiary': 'rgb(var(--gs-tertiary) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--gs-on-tertiary-fixed-variant) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--gs-on-secondary-fixed-variant) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--gs-on-secondary-container) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--gs-surface-container-low) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--gs-tertiary-fixed) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--gs-tertiary-fixed-dim) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--gs-on-tertiary-fixed) / <alpha-value>)',
                'on-secondary': 'rgb(var(--gs-on-secondary) / <alpha-value>)',
            },
            fontFamily: {
                'display-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'body-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-md': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'gutter': '1rem',
                'margin-mobile': '1rem',
                'margin-desktop': '2rem',
            },
        },
    },
};
