<?php

namespace App\Domain\BizBoost\Entities;

class Business
{
    public function __construct(
        public readonly ?int $id,
        public readonly int $userId,
        public readonly ?int $organizationId,
        public readonly string $name,
        public readonly string $slug,
        public readonly ?string $description,
        public readonly ?string $logoPath,
        public readonly ?string $industry,
        public readonly ?string $address,
        public readonly ?string $city,
        public readonly ?string $province,
        public readonly ?string $country,
        public readonly ?string $phone,
        public readonly ?string $whatsapp,
        public readonly ?string $email,
        public readonly ?string $website,
        public readonly ?string $timezone,
        public readonly ?string $locale,
        public readonly ?string $currency,
        public readonly ?array $socialLinks,
        public readonly ?array $businessHours,
        public readonly ?array $settings,
        public readonly ?array $whiteLabelConfig,
        public readonly bool $isActive,
        public readonly bool $onboardingCompleted,
        public readonly bool $marketplaceListed,
        public readonly ?string $marketplaceListedAt,
        public readonly ?int $marketplaceSellerId,
        public readonly bool $marketplaceSyncEnabled,
        public readonly ?string $marketplaceSyncedAt,
        public readonly ?string $createdAt,
        public readonly ?string $updatedAt,
    ) {}

    public static function reconstitute(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            userId: (int) ($data['user_id'] ?? 0),
            organizationId: isset($data['organization_id']) ? (int) $data['organization_id'] : null,
            name: $data['name'],
            slug: $data['slug'],
            description: $data['description'] ?? null,
            logoPath: $data['logo_path'] ?? null,
            industry: $data['industry'] ?? null,
            address: $data['address'] ?? null,
            city: $data['city'] ?? null,
            province: $data['province'] ?? null,
            country: $data['country'] ?? null,
            phone: $data['phone'] ?? null,
            whatsapp: $data['whatsapp'] ?? null,
            email: $data['email'] ?? null,
            website: $data['website'] ?? null,
            timezone: $data['timezone'] ?? null,
            locale: $data['locale'] ?? null,
            currency: $data['currency'] ?? null,
            socialLinks: $data['social_links'] ?? null,
            businessHours: $data['business_hours'] ?? null,
            settings: $data['settings'] ?? null,
            whiteLabelConfig: $data['white_label_config'] ?? null,
            isActive: (bool) ($data['is_active'] ?? true),
            onboardingCompleted: (bool) ($data['onboarding_completed'] ?? false),
            marketplaceListed: (bool) ($data['marketplace_listed'] ?? false),
            marketplaceListedAt: $data['marketplace_listed_at'] ?? null,
            marketplaceSellerId: isset($data['marketplace_seller_id']) ? (int) $data['marketplace_seller_id'] : null,
            marketplaceSyncEnabled: (bool) ($data['marketplace_sync_enabled'] ?? false),
            marketplaceSyncedAt: $data['marketplace_synced_at'] ?? null,
            createdAt: $data['created_at'] ?? null,
            updatedAt: $data['updated_at'] ?? null,
        );
    }

    public static function create(array $data): self
    {
        return new self(
            id: null,
            userId: (int) $data['user_id'],
            organizationId: isset($data['organization_id']) ? (int) $data['organization_id'] : null,
            name: $data['name'],
            slug: $data['slug'],
            description: $data['description'] ?? null,
            logoPath: null,
            industry: $data['industry'] ?? null,
            address: $data['address'] ?? null,
            city: $data['city'] ?? null,
            province: $data['province'] ?? null,
            country: 'Zambia',
            phone: $data['phone'] ?? null,
            whatsapp: $data['whatsapp'] ?? null,
            email: $data['email'] ?? null,
            website: null,
            timezone: null,
            locale: null,
            currency: 'ZMW',
            socialLinks: null,
            businessHours: null,
            settings: null,
            whiteLabelConfig: null,
            isActive: true,
            onboardingCompleted: false,
            marketplaceListed: false,
            marketplaceListedAt: null,
            marketplaceSellerId: null,
            marketplaceSyncEnabled: false,
            marketplaceSyncedAt: null,
            createdAt: null,
            updatedAt: null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'user_id' => $this->userId,
            'organization_id' => $this->organizationId,
            'name' => $this->name,
            'slug' => $this->slug,
            'description' => $this->description,
            'logo_path' => $this->logoPath,
            'industry' => $this->industry,
            'address' => $this->address,
            'city' => $this->city,
            'province' => $this->province,
            'country' => $this->country,
            'phone' => $this->phone,
            'whatsapp' => $this->whatsapp,
            'email' => $this->email,
            'website' => $this->website,
            'timezone' => $this->timezone,
            'locale' => $this->locale,
            'currency' => $this->currency,
            'social_links' => $this->socialLinks,
            'business_hours' => $this->businessHours,
            'settings' => $this->settings,
            'white_label_config' => $this->whiteLabelConfig,
            'is_active' => $this->isActive,
            'onboarding_completed' => $this->onboardingCompleted,
            'marketplace_listed' => $this->marketplaceListed,
            'marketplace_listed_at' => $this->marketplaceListedAt,
            'marketplace_seller_id' => $this->marketplaceSellerId,
            'marketplace_sync_enabled' => $this->marketplaceSyncEnabled,
            'marketplace_synced_at' => $this->marketplaceSyncedAt,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
        ];
    }
}