<?php

namespace App\Domain\BizBoost\Entities;

class BusinessProfile
{
    public function __construct(
        public readonly ?int $id,
        public readonly int $businessId,
        public readonly ?string $heroImagePath,
        public readonly ?string $aboutImagePath,
        public readonly ?string $bannerImagePath,
        public readonly ?string $about,
        public readonly ?string $businessStory,
        public readonly ?string $mission,
        public readonly ?string $vision,
        public readonly ?int $foundingYear,
        public readonly ?array $businessHours,
        public readonly ?array $teamMembers,
        public readonly ?array $achievements,
        public readonly ?array $services,
        public readonly ?array $testimonials,
        public readonly ?string $tagline,
        public readonly ?string $contactEmail,
        public readonly ?array $galleryImages,
        public readonly ?array $seoMeta,
        public readonly ?array $themeSettings,
        public readonly bool $showProducts,
        public readonly bool $showServices,
        public readonly bool $showGallery,
        public readonly bool $showTestimonials,
        public readonly bool $showBusinessHours,
        public readonly bool $showContactForm,
        public readonly bool $showWhatsappButton,
        public readonly bool $showSocialLinks,
        public readonly bool $isPublished,
        public readonly ?string $createdAt,
        public readonly ?string $updatedAt,
    ) {}

    public static function reconstitute(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            businessId: (int) $data['business_id'],
            heroImagePath: $data['hero_image_path'] ?? null,
            aboutImagePath: $data['about_image_path'] ?? null,
            bannerImagePath: $data['banner_image_path'] ?? null,
            about: $data['about'] ?? null,
            businessStory: $data['business_story'] ?? null,
            mission: $data['mission'] ?? null,
            vision: $data['vision'] ?? null,
            foundingYear: isset($data['founding_year']) ? (int) $data['founding_year'] : null,
            businessHours: $data['business_hours'] ?? null,
            teamMembers: $data['team_members'] ?? null,
            achievements: $data['achievements'] ?? null,
            services: $data['services'] ?? null,
            testimonials: $data['testimonials'] ?? null,
            tagline: $data['tagline'] ?? null,
            contactEmail: $data['contact_email'] ?? null,
            galleryImages: $data['gallery_images'] ?? null,
            seoMeta: $data['seo_meta'] ?? null,
            themeSettings: $data['theme_settings'] ?? null,
            showProducts: (bool) ($data['show_products'] ?? true),
            showServices: (bool) ($data['show_services'] ?? true),
            showGallery: (bool) ($data['show_gallery'] ?? false),
            showTestimonials: (bool) ($data['show_testimonials'] ?? false),
            showBusinessHours: (bool) ($data['show_business_hours'] ?? true),
            showContactForm: (bool) ($data['show_contact_form'] ?? true),
            showWhatsappButton: (bool) ($data['show_whatsapp_button'] ?? true),
            showSocialLinks: (bool) ($data['show_social_links'] ?? true),
            isPublished: (bool) ($data['is_published'] ?? false),
            createdAt: $data['created_at'] ?? null,
            updatedAt: $data['updated_at'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'business_id' => $this->businessId,
            'hero_image_path' => $this->heroImagePath,
            'about_image_path' => $this->aboutImagePath,
            'banner_image_path' => $this->bannerImagePath,
            'about' => $this->about,
            'business_story' => $this->businessStory,
            'mission' => $this->mission,
            'vision' => $this->vision,
            'founding_year' => $this->foundingYear,
            'business_hours' => $this->businessHours,
            'team_members' => $this->teamMembers,
            'achievements' => $this->achievements,
            'services' => $this->services,
            'testimonials' => $this->testimonials,
            'tagline' => $this->tagline,
            'contact_email' => $this->contactEmail,
            'gallery_images' => $this->galleryImages,
            'seo_meta' => $this->seoMeta,
            'theme_settings' => $this->themeSettings,
            'show_products' => $this->showProducts,
            'show_services' => $this->showServices,
            'show_gallery' => $this->showGallery,
            'show_testimonials' => $this->showTestimonials,
            'show_business_hours' => $this->showBusinessHours,
            'show_contact_form' => $this->showContactForm,
            'show_whatsapp_button' => $this->showWhatsappButton,
            'show_social_links' => $this->showSocialLinks,
            'is_published' => $this->isPublished,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
        ];
    }
}