<?php

return [
    'id' => 'growbuilder',
    'name' => 'GrowBuilder',
    'slug' => 'growbuilder',
    'description' => 'Professional website builder for Zambian businesses',
    'category' => 'business',
    'status' => 'active',
    'version' => '1.0.0',
    'account_types' => ['member', 'business'],
    'requires_subscription' => true,
    'icon' => 'GlobeAltIcon',
    'color' => 'blue',
    'routes' => [
        'integrated' => '/growbuilder',
        'standalone' => '/growbuilder',
    ],
    'pwa' => [
        'enabled' => true,
        'installable' => true,
    ],

    'feature_labels' => [
        'sites' => 'Sites',
        'storage_mb' => 'Storage',
        'products' => 'Products',
        'ai_prompts' => 'AI Prompts / month',
        'subdomain' => 'Free Subdomain',
        'custom_domain' => 'Custom Domain',
        'limited_templates' => 'Limited Templates',
        'basic_editor' => 'Basic Editor',
        'ecommerce' => 'E-Commerce',
        'manual_payments' => 'Manual Payments',
        'payment_integration' => 'Payment Gateway Integration',
        'unlimited_products' => 'Unlimited Products',
        'shared_smtp' => 'Shared SMTP',
        'own_smtp' => 'Custom SMTP',
        'marketing_tools' => 'Marketing Tools',
        'remove_branding' => 'Remove GrowBuilder Branding',
        'ai_section_generator' => 'AI Section Generator',
        'ai_seo' => 'AI SEO Assistant',
        'ai_priority' => 'AI Priority Access',
        'ai_early_access' => 'Early AI Features',
        'free_domain_after_3mo' => 'Free Domain (after 3 months)',
        'priority_support' => 'Priority Support',
        'static_export' => 'Static Export',
        'white_label' => 'White Label',
        'multi_site' => 'Multi-Site Management',
        'team_members' => 'Team Members',
        'analytics' => 'Advanced Analytics',
    ],

    'limit_labels' => [
        'sites' => 'Sites',
        'storage_mb' => 'Storage',
        'products' => 'Products',
        'ai_prompts' => 'AI Prompts',
        'team_members' => 'Team Members',
    ],

    'tiers' => [
        'free' => [
            'name' => 'Free',
            'description' => 'Try it out — build your first site at no cost',
            'price_monthly' => 0,
            'price_annual' => 0,
            'popular' => false,
            'sort_order' => 0,
            'limits' => [
                'sites' => 1,
                'storage_mb' => 500,
                'products' => 0,
                'ai_prompts' => 50,
                'team_members' => 1,
            ],
            'features' => [
                'subdomain',
                'limited_templates',
                'basic_editor',
            ],
        ],

        'starter' => [
            'name' => 'Starter',
            'description' => 'Essential tools for a professional online presence',
            'price_monthly' => 149,
            'price_annual' => 1429,
            'popular' => true,
            'sort_order' => 1,
            'limits' => [
                'sites' => 1,
                'storage_mb' => 1024,
                'products' => 20,
                'ai_prompts' => 100,
                'team_members' => 1,
            ],
            'features' => [
                'subdomain',
                'custom_domain',
                'ecommerce',
                'manual_payments',
                'shared_smtp',
                'ai_section_generator',
            ],
        ],

        'business' => [
            'name' => 'Business',
            'description' => 'Full power for growing your online sales',
            'price_monthly' => 399,
            'price_annual' => 3830,
            'popular' => false,
            'sort_order' => 2,
            'limits' => [
                'sites' => 3,
                'storage_mb' => 2048,
                'products' => -1,
                'ai_prompts' => -1,
                'team_members' => 5,
            ],
            'features' => [
                'subdomain',
                'custom_domain',
                'free_domain_after_3mo',
                'ecommerce',
                'payment_integration',
                'unlimited_products',
                'marketing_tools',
                'remove_branding',
                'own_smtp',
                'ai_section_generator',
                'ai_seo',
                'priority_support',
                'static_export',
                'analytics',
            ],
        ],

        'agency' => [
            'name' => 'Agency',
            'description' => 'Manage multiple client sites under one account',
            'price_monthly' => 999,
            'price_annual' => 9590,
            'popular' => false,
            'sort_order' => 3,
            'limits' => [
                'sites' => 20,
                'storage_mb' => 10240,
                'products' => -1,
                'ai_prompts' => -1,
                'team_members' => 20,
            ],
            'features' => [
                'subdomain',
                'custom_domain',
                'free_domain_after_3mo',
                'ecommerce',
                'payment_integration',
                'unlimited_products',
                'marketing_tools',
                'remove_branding',
                'own_smtp',
                'ai_section_generator',
                'ai_seo',
                'ai_priority',
                'ai_early_access',
                'priority_support',
                'static_export',
                'white_label',
                'multi_site',
                'analytics',
            ],
        ],
    ],

    'usage_metrics' => [
        'ai_prompts' => [
            'label' => 'AI Prompts',
            'period' => 'monthly',
            'reset_day' => 1,
        ],
    ],
];
